# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoPrint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payeecompany',
            old_name='收款人开户行',
            new_name='account_location',
        ),
        migrations.RenameField(
            model_name='payeecompany',
            old_name='收款人账号',
            new_name='company_account',
        ),
        migrations.RenameField(
            model_name='payeecompany',
            old_name='收款人地址',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='payeecompany',
            old_name='公司名称',
            new_name='company_name',
        ),
    ]
