# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 05:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoPrint', '0008_auto_20170629_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='payeecompany',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期'),
        ),
    ]
