# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoPrint', '0009_payeecompany_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salereport',
            old_name='receipt_account',
            new_name='receipt_amount',
        ),
    ]
