# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoPrint', '0010_auto_20170629_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereport',
            name='receipt_amount',
            field=models.IntegerField(verbose_name='附寄单证张数'),
        ),
    ]
